// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Square_59eb3b3a74ef2544cbd0bb383d729383Index = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Square_59eb3b3a74ef2544cbd0bb383d729383", 0 },

		};
	}
}
