// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Backgroud_daf2ee43443998c43b7845ac6f687f8bIndex = 0;
		public const int MiniGameManager_759334206ec3a2d46b848ec8d2431208Index = 1;
		public const int Player0_1b8b60cb7c844004ba711d3409682a23Index = 2;
		public const int Player1_358f1ade9e8606544972b75cb628cfd9Index = 3;
		public const int Sprite__char_32_Potato_9695b90e9288dc943beda0d6f17570feIndex = 4;
		public const int Square_59eb3b3a74ef2544cbd0bb383d729383Index = 5;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Backgroud_daf2ee43443998c43b7845ac6f687f8b", 0 },

			{ "MiniGameManager_759334206ec3a2d46b848ec8d2431208", 1 },

			{ "Player0_1b8b60cb7c844004ba711d3409682a23", 2 },

			{ "Player1_358f1ade9e8606544972b75cb628cfd9", 3 },

			{ "Sprite__char_32_Potato_9695b90e9288dc943beda0d6f17570fe", 4 },

			{ "Square_59eb3b3a74ef2544cbd0bb383d729383", 5 },

		};
	}
}
