// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_9695b90e9288dc943beda0d6f17570fe_3cd78dc1_8f44_4954_af45_909af13038ba : Vector2Binding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector2 Value
		{
			get => (Vector2)(UnityEngine.Vector2)(CastedUnityComponent.size);
			set => CastedUnityComponent.size = (UnityEngine.Vector2)(value);
		}

		protected override Vector2 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.size;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.size = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_b32a7255_a00b_4986_ab0d_d95a854232b4 : FloatBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.adaptiveModeThreshold);
			set => CastedUnityComponent.adaptiveModeThreshold = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.adaptiveModeThreshold;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.adaptiveModeThreshold = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_17bd950b_cd7b_4403_b75e_51c56d7ec389 : ColorBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Color Value
		{
			get => (Color)(UnityEngine.Color)(CastedUnityComponent.color);
			set => CastedUnityComponent.color = (UnityEngine.Color)(value);
		}

		protected override Color ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.color;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.color = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_39626318_5bec_45c5_97b3_aefedc8e7b2a : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.flipX);
			set => CastedUnityComponent.flipX = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.flipX;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.flipX = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_636fa417_9e86_45b1_a82d_1fa5614da307 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.flipY);
			set => CastedUnityComponent.flipY = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.flipY;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.flipY = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_37c767d1_fc24_42f7_a9c1_78f08d618e06 : ReferenceBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000000100000;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.probeAnchor);
			set => CastedUnityComponent.probeAnchor = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.lightProbeAnchor;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.lightProbeAnchor = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_55693119_da24_4000_9b40_cdebfae0aa14 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000001000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.castShadows);
			set => CastedUnityComponent.castShadows = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.castShadows;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.castShadows = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_4e0f81b7_56e6_48f1_8b16_ebba0bb883d1 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000010000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.motionVectors);
			set => CastedUnityComponent.motionVectors = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.motionVectors;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.motionVectors = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_4b392408_2433_4c48_8ba1_0d82e0f3d1bc : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000000100000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.useLightProbes);
			set => CastedUnityComponent.useLightProbes = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.useLightProbes;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.useLightProbes = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_bb0fb577_deec_493d_aad9_3f533d752460 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000001000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.enabled;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_0cef1afd_6a41_455d_b265_4f6a65f2d1c6 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000010000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.receiveShadows);
			set => CastedUnityComponent.receiveShadows = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.receiveShadows;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.receiveShadows = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_e7507981_d53e_490f_bea4_6d23311e78cd : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000000100000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.forceRenderingOff);
			set => CastedUnityComponent.forceRenderingOff = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.forceRenderingOff;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.forceRenderingOff = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_b708b727_5edc_4f89_b2a5_7af8595ebcf2 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000001000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.staticShadowCaster);
			set => CastedUnityComponent.staticShadowCaster = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.staticShadowCaster;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.staticShadowCaster = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_308393dc_7e2b_4d4b_8c1a_cdcb9206e9d2 : UIntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000010000000000000;

		public override uint Value
		{
			get => (uint)(System.UInt32)(CastedUnityComponent.renderingLayerMask);
			set => CastedUnityComponent.renderingLayerMask = (System.UInt32)(value);
		}

		protected override uint ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.renderingLayerMask;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.renderingLayerMask = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_9a1e515a_19d8_4b9d_811e_2902131bb97b : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000000100000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.rendererPriority);
			set => CastedUnityComponent.rendererPriority = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.rendererPriority;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.rendererPriority = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_91f4dc29_e7cd_42ae_8dca_dab7d198ec33 : StringBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000001000000000000000;

		public override string Value
		{
			get => (string)(System.String)(CastedUnityComponent.sortingLayerName);
			set => CastedUnityComponent.sortingLayerName = (System.String)(value);
		}

		protected override string ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.sortingLayerName;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.sortingLayerName = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_7336b3b3_3cea_44c8_b9c8_7fe980d111dd : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000010000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.sortingLayerID);
			set => CastedUnityComponent.sortingLayerID = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.sortingLayerID;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.sortingLayerID = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_e0514b8b_60f2_487f_b8eb_1e41d904f0f9 : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000000100000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.sortingOrder);
			set => CastedUnityComponent.sortingOrder = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.sortingOrder;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.sortingOrder = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_46c20a9a_e8cc_4dc6_880a_c26a6ed53a0e : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000001000000000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.allowOcclusionWhenDynamic);
			set => CastedUnityComponent.allowOcclusionWhenDynamic = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.allowOcclusionWhenDynamic;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.allowOcclusionWhenDynamic = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_9c062a78_fcb7_4bf0_bfbd_aa898c2107f1 : ReferenceBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000010000000000000000000;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.lightProbeProxyVolumeOverride);
			set => CastedUnityComponent.lightProbeProxyVolumeOverride = coherenceSync.MonoBridge.EntityIdToGameObject(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.lightProbeProxyVolumeOverride;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.lightProbeProxyVolumeOverride = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_6245612c_ff5d_4947_aafd_e60dd3dc8ea8 : ReferenceBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000000100000000000000000000;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.probeAnchor);
			set => CastedUnityComponent.probeAnchor = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.probeAnchor;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.probeAnchor = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_89eab69e_0454_4c36_adce_212283d614c0 : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000001000000000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.lightmapIndex);
			set => CastedUnityComponent.lightmapIndex = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.lightmapIndex;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.lightmapIndex = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}

	public class Binding_9695b90e9288dc943beda0d6f17570fe_5673f60d_9432_4523_a3ca_ed611009fb5d : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270";

		public override uint FieldMask => 0b00000000010000000000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.realtimeLightmapIndex);
			set => CastedUnityComponent.realtimeLightmapIndex = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			return update.realtimeLightmapIndex;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270)coherenceComponent;
			update.realtimeLightmapIndex = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Sprite Potato' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncSprite__char_32_Potato : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncSprite__char_32_Potato>();
			if (coherenceSync.TryGetBindingByGuid("3cd78dc1-8f44-4954-af45-909af13038ba", "size", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_size))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_3cd78dc1_8f44_4954_af45_909af13038ba();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_size.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_size)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).size");
			}
			if (coherenceSync.TryGetBindingByGuid("b32a7255-a00b-4986-ab0d-d95a854232b4", "adaptiveModeThreshold", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_adaptiveModeThreshold))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_b32a7255_a00b_4986_ab0d_d95a854232b4();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_adaptiveModeThreshold.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_adaptiveModeThreshold)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).adaptiveModeThreshold");
			}
			if (coherenceSync.TryGetBindingByGuid("17bd950b-cd7b-4403-b75e-51c56d7ec389", "color", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_color))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_17bd950b_cd7b_4403_b75e_51c56d7ec389();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_color.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_color)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).color");
			}
			if (coherenceSync.TryGetBindingByGuid("39626318-5bec-45c5-97b3-aefedc8e7b2a", "flipX", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_flipX))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_39626318_5bec_45c5_97b3_aefedc8e7b2a();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_flipX.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_flipX)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).flipX");
			}
			if (coherenceSync.TryGetBindingByGuid("636fa417-9e86-45b1-a82d-1fa5614da307", "flipY", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_flipY))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_636fa417_9e86_45b1_a82d_1fa5614da307();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_flipY.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_flipY)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).flipY");
			}
			if (coherenceSync.TryGetBindingByGuid("37c767d1-fc24-42f7-a9c1-78f08d618e06", "lightProbeAnchor", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightProbeAnchor))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_37c767d1_fc24_42f7_a9c1_78f08d618e06();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightProbeAnchor.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightProbeAnchor)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).lightProbeAnchor");
			}
			if (coherenceSync.TryGetBindingByGuid("55693119-da24-4000-9b40-cdebfae0aa14", "castShadows", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_castShadows))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_55693119_da24_4000_9b40_cdebfae0aa14();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_castShadows.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_castShadows)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).castShadows");
			}
			if (coherenceSync.TryGetBindingByGuid("4e0f81b7-56e6-48f1-8b16-ebba0bb883d1", "motionVectors", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_motionVectors))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_4e0f81b7_56e6_48f1_8b16_ebba0bb883d1();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_motionVectors.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_motionVectors)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).motionVectors");
			}
			if (coherenceSync.TryGetBindingByGuid("4b392408-2433-4c48-8ba1-0d82e0f3d1bc", "useLightProbes", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_useLightProbes))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_4b392408_2433_4c48_8ba1_0d82e0f3d1bc();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_useLightProbes.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_useLightProbes)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).useLightProbes");
			}
			if (coherenceSync.TryGetBindingByGuid("bb0fb577-deec-493d-aad9-3f533d752460", "enabled", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_enabled))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_bb0fb577_deec_493d_aad9_3f533d752460();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("0cef1afd-6a41-455d-b265-4f6a65f2d1c6", "receiveShadows", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_receiveShadows))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_0cef1afd_6a41_455d_b265_4f6a65f2d1c6();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_receiveShadows.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_receiveShadows)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).receiveShadows");
			}
			if (coherenceSync.TryGetBindingByGuid("e7507981-d53e-490f-bea4-6d23311e78cd", "forceRenderingOff", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_forceRenderingOff))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_e7507981_d53e_490f_bea4_6d23311e78cd();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_forceRenderingOff.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_forceRenderingOff)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).forceRenderingOff");
			}
			if (coherenceSync.TryGetBindingByGuid("b708b727-5edc-4f89-b2a5-7af8595ebcf2", "staticShadowCaster", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_staticShadowCaster))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_b708b727_5edc_4f89_b2a5_7af8595ebcf2();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_staticShadowCaster.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_staticShadowCaster)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).staticShadowCaster");
			}
			if (coherenceSync.TryGetBindingByGuid("308393dc-7e2b-4d4b-8c1a-cdcb9206e9d2", "renderingLayerMask", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_renderingLayerMask))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_308393dc_7e2b_4d4b_8c1a_cdcb9206e9d2();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_renderingLayerMask.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_renderingLayerMask)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).renderingLayerMask");
			}
			if (coherenceSync.TryGetBindingByGuid("9a1e515a-19d8-4b9d-811e-2902131bb97b", "rendererPriority", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_rendererPriority))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_9a1e515a_19d8_4b9d_811e_2902131bb97b();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_rendererPriority.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_rendererPriority)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).rendererPriority");
			}
			if (coherenceSync.TryGetBindingByGuid("91f4dc29-e7cd-42ae-8dca-dab7d198ec33", "sortingLayerName", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingLayerName))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_91f4dc29_e7cd_42ae_8dca_dab7d198ec33();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingLayerName.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingLayerName)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).sortingLayerName");
			}
			if (coherenceSync.TryGetBindingByGuid("7336b3b3-3cea-44c8-b9c8-7fe980d111dd", "sortingLayerID", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingLayerID))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_7336b3b3_3cea_44c8_b9c8_7fe980d111dd();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingLayerID.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingLayerID)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).sortingLayerID");
			}
			if (coherenceSync.TryGetBindingByGuid("e0514b8b-60f2-487f-b8eb-1e41d904f0f9", "sortingOrder", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingOrder))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_e0514b8b_60f2_487f_b8eb_1e41d904f0f9();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingOrder.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_sortingOrder)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).sortingOrder");
			}
			if (coherenceSync.TryGetBindingByGuid("46c20a9a-e8cc-4dc6-880a-c26a6ed53a0e", "allowOcclusionWhenDynamic", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_allowOcclusionWhenDynamic))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_46c20a9a_e8cc_4dc6_880a_c26a6ed53a0e();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_allowOcclusionWhenDynamic.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_allowOcclusionWhenDynamic)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).allowOcclusionWhenDynamic");
			}
			if (coherenceSync.TryGetBindingByGuid("9c062a78-fcb7-4bf0-bfbd-aa898c2107f1", "lightProbeProxyVolumeOverride", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightProbeProxyVolumeOverride))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_9c062a78_fcb7_4bf0_bfbd_aa898c2107f1();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightProbeProxyVolumeOverride.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightProbeProxyVolumeOverride)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).lightProbeProxyVolumeOverride");
			}
			if (coherenceSync.TryGetBindingByGuid("6245612c-ff5d-4947-aafd-e60dd3dc8ea8", "probeAnchor", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_probeAnchor))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_6245612c_ff5d_4947_aafd_e60dd3dc8ea8();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_probeAnchor.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_probeAnchor)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).probeAnchor");
			}
			if (coherenceSync.TryGetBindingByGuid("89eab69e-0454-4c36-adce-212283d614c0", "lightmapIndex", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightmapIndex))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_89eab69e_0454_4c36_adce_212283d614c0();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightmapIndex.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_lightmapIndex)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).lightmapIndex");
			}
			if (coherenceSync.TryGetBindingByGuid("5673f60d-9432-4523-a3ca-ed611009fb5d", "realtimeLightmapIndex", out Binding InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_realtimeLightmapIndex))
			{
				var clone = new Binding_9695b90e9288dc943beda0d6f17570fe_5673f60d_9432_4523_a3ca_ed611009fb5d();
				InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_realtimeLightmapIndex.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalSprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_Sprite__char_32_Potato_UnityEngine__char_46_SpriteRenderer_26267408122474270_realtimeLightmapIndex)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).realtimeLightmapIndex");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncSprite__char_32_Potato] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
