// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_70316beb_3ef2_4971_a729_825a58eeba76 : ColorBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Color Value
		{
			get => (Color)(UnityEngine.Color)(CastedUnityComponent.color);
			set => CastedUnityComponent.color = (UnityEngine.Color)(value);
		}

		protected override Color ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.color;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.color = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_682c5b7b_10ba_4f52_88fd_f065a40642ef : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.enabled;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_77e9ef30_ebb9_4418_a207_a6212267dc5f : UIntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override uint Value
		{
			get => (uint)(System.UInt32)(CastedUnityComponent.renderingLayerMask);
			set => CastedUnityComponent.renderingLayerMask = (System.UInt32)(value);
		}

		protected override uint ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.renderingLayerMask;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.renderingLayerMask = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_688fa9b9_09e2_4776_a716_752620c79188 : Vector2Binding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override Vector2 Value
		{
			get => (Vector2)(UnityEngine.Vector2)(CastedUnityComponent.size);
			set => CastedUnityComponent.size = (UnityEngine.Vector2)(value);
		}

		protected override Vector2 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.size;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.size = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_f3fee9df_4384_447f_bb7c_076fe06692ce : FloatBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.adaptiveModeThreshold);
			set => CastedUnityComponent.adaptiveModeThreshold = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.adaptiveModeThreshold;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.adaptiveModeThreshold = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_2b6a821e_2705_44a4_9d5f_1758d3e54021 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000000100000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.flipX);
			set => CastedUnityComponent.flipX = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.flipX;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.flipX = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_4b611792_dfd2_4ff0_84b6_31432f2b2f72 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000001000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.flipY);
			set => CastedUnityComponent.flipY = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.flipY;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.flipY = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_0fd464d6_0e6a_46b2_b87a_4bd96a1a0911 : ReferenceBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000010000000;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.probeAnchor);
			set => CastedUnityComponent.probeAnchor = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.lightProbeAnchor;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.lightProbeAnchor = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_91555140_8c2e_4319_a9ef_86c9d427bb96 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000000100000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.castShadows);
			set => CastedUnityComponent.castShadows = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.castShadows;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.castShadows = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_f7261aa5_e681_4bb8_be48_4a0e5f9234d9 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000001000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.motionVectors);
			set => CastedUnityComponent.motionVectors = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.motionVectors;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.motionVectors = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_b3abe6f4_fdfd_4748_9e50_c39b9632ebd5 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000010000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.useLightProbes);
			set => CastedUnityComponent.useLightProbes = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.useLightProbes;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.useLightProbes = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_5442faec_6d19_40d2_9ca8_f75a5a6d2016 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000000100000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.receiveShadows);
			set => CastedUnityComponent.receiveShadows = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.receiveShadows;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.receiveShadows = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_d7d5cf6e_edd2_4e9e_9e22_3763aba9c863 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000001000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.forceRenderingOff);
			set => CastedUnityComponent.forceRenderingOff = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.forceRenderingOff;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.forceRenderingOff = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_22c899da_247a_45da_9d2b_e194319bd934 : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000010000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.staticShadowCaster);
			set => CastedUnityComponent.staticShadowCaster = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.staticShadowCaster;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.staticShadowCaster = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_0231930c_edce_4055_afb1_739b87dfe5ec : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000000100000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.rendererPriority);
			set => CastedUnityComponent.rendererPriority = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.rendererPriority;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.rendererPriority = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_2e8c3d98_caa8_4d89_b48a_ee6874e9b56e : StringBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000001000000000000000;

		public override string Value
		{
			get => (string)(System.String)(CastedUnityComponent.sortingLayerName);
			set => CastedUnityComponent.sortingLayerName = (System.String)(value);
		}

		protected override string ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.sortingLayerName;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.sortingLayerName = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_31b2e83b_4f43_4709_8912_29042d0b60bd : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000010000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.sortingLayerID);
			set => CastedUnityComponent.sortingLayerID = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.sortingLayerID;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.sortingLayerID = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_cf215880_f8c1_4c78_8a08_62b39f6e83a4 : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000000100000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.sortingOrder);
			set => CastedUnityComponent.sortingOrder = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.sortingOrder;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.sortingOrder = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_eb2b888b_e883_491c_9e87_92d2faf1a01c : BoolBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000001000000000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.allowOcclusionWhenDynamic);
			set => CastedUnityComponent.allowOcclusionWhenDynamic = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.allowOcclusionWhenDynamic;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.allowOcclusionWhenDynamic = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_09f31160_7485_40ab_a284_2df7eaf788a0 : ReferenceBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000010000000000000000000;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.lightProbeProxyVolumeOverride);
			set => CastedUnityComponent.lightProbeProxyVolumeOverride = coherenceSync.MonoBridge.EntityIdToGameObject(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.lightProbeProxyVolumeOverride;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.lightProbeProxyVolumeOverride = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_75194212_5b17_4f2b_9bf0_2afd37a669f9 : ReferenceBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000000100000000000000000000;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.probeAnchor);
			set => CastedUnityComponent.probeAnchor = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.probeAnchor;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.probeAnchor = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_713ce5cc_bd4d_40cd_829b_da740ac92ec1 : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000001000000000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.lightmapIndex);
			set => CastedUnityComponent.lightmapIndex = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.lightmapIndex;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.lightmapIndex = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}

	public class Binding_daf2ee43443998c43b7845ac6f687f8b_172b2811_d6ec_4a79_b931_324636a65df9 : IntBinding
	{
		private UnityEngine.SpriteRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.SpriteRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648";

		public override uint FieldMask => 0b00000000010000000000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.realtimeLightmapIndex);
			set => CastedUnityComponent.realtimeLightmapIndex = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			return update.realtimeLightmapIndex;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648)coherenceComponent;
			update.realtimeLightmapIndex = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Backgroud' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncBackgroud : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncBackgroud>();
			if (coherenceSync.TryGetBindingByGuid("70316beb-3ef2-4971-a729-825a58eeba76", "color", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_color))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_70316beb_3ef2_4971_a729_825a58eeba76();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_color.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_color)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).color");
			}
			if (coherenceSync.TryGetBindingByGuid("682c5b7b-10ba-4f52-88fd-f065a40642ef", "enabled", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_enabled))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_682c5b7b_10ba_4f52_88fd_f065a40642ef();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("77e9ef30-ebb9-4418-a207-a6212267dc5f", "renderingLayerMask", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_renderingLayerMask))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_77e9ef30_ebb9_4418_a207_a6212267dc5f();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_renderingLayerMask.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_renderingLayerMask)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).renderingLayerMask");
			}
			if (coherenceSync.TryGetBindingByGuid("688fa9b9-09e2-4776-a716-752620c79188", "size", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_size))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_688fa9b9_09e2_4776_a716_752620c79188();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_size.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_size)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).size");
			}
			if (coherenceSync.TryGetBindingByGuid("f3fee9df-4384-447f-bb7c-076fe06692ce", "adaptiveModeThreshold", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_adaptiveModeThreshold))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_f3fee9df_4384_447f_bb7c_076fe06692ce();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_adaptiveModeThreshold.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_adaptiveModeThreshold)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).adaptiveModeThreshold");
			}
			if (coherenceSync.TryGetBindingByGuid("2b6a821e-2705-44a4-9d5f-1758d3e54021", "flipX", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_flipX))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_2b6a821e_2705_44a4_9d5f_1758d3e54021();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_flipX.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_flipX)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).flipX");
			}
			if (coherenceSync.TryGetBindingByGuid("4b611792-dfd2-4ff0-84b6-31432f2b2f72", "flipY", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_flipY))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_4b611792_dfd2_4ff0_84b6_31432f2b2f72();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_flipY.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_flipY)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).flipY");
			}
			if (coherenceSync.TryGetBindingByGuid("0fd464d6-0e6a-46b2-b87a-4bd96a1a0911", "lightProbeAnchor", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightProbeAnchor))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_0fd464d6_0e6a_46b2_b87a_4bd96a1a0911();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightProbeAnchor.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightProbeAnchor)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).lightProbeAnchor");
			}
			if (coherenceSync.TryGetBindingByGuid("91555140-8c2e-4319-a9ef-86c9d427bb96", "castShadows", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_castShadows))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_91555140_8c2e_4319_a9ef_86c9d427bb96();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_castShadows.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_castShadows)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).castShadows");
			}
			if (coherenceSync.TryGetBindingByGuid("f7261aa5-e681-4bb8-be48-4a0e5f9234d9", "motionVectors", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_motionVectors))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_f7261aa5_e681_4bb8_be48_4a0e5f9234d9();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_motionVectors.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_motionVectors)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).motionVectors");
			}
			if (coherenceSync.TryGetBindingByGuid("b3abe6f4-fdfd-4748-9e50-c39b9632ebd5", "useLightProbes", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_useLightProbes))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_b3abe6f4_fdfd_4748_9e50_c39b9632ebd5();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_useLightProbes.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_useLightProbes)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).useLightProbes");
			}
			if (coherenceSync.TryGetBindingByGuid("5442faec-6d19-40d2-9ca8-f75a5a6d2016", "receiveShadows", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_receiveShadows))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_5442faec_6d19_40d2_9ca8_f75a5a6d2016();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_receiveShadows.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_receiveShadows)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).receiveShadows");
			}
			if (coherenceSync.TryGetBindingByGuid("d7d5cf6e-edd2-4e9e-9e22-3763aba9c863", "forceRenderingOff", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_forceRenderingOff))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_d7d5cf6e_edd2_4e9e_9e22_3763aba9c863();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_forceRenderingOff.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_forceRenderingOff)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).forceRenderingOff");
			}
			if (coherenceSync.TryGetBindingByGuid("22c899da-247a-45da-9d2b-e194319bd934", "staticShadowCaster", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_staticShadowCaster))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_22c899da_247a_45da_9d2b_e194319bd934();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_staticShadowCaster.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_staticShadowCaster)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).staticShadowCaster");
			}
			if (coherenceSync.TryGetBindingByGuid("0231930c-edce-4055-afb1-739b87dfe5ec", "rendererPriority", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_rendererPriority))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_0231930c_edce_4055_afb1_739b87dfe5ec();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_rendererPriority.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_rendererPriority)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).rendererPriority");
			}
			if (coherenceSync.TryGetBindingByGuid("2e8c3d98-caa8-4d89-b48a-ee6874e9b56e", "sortingLayerName", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingLayerName))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_2e8c3d98_caa8_4d89_b48a_ee6874e9b56e();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingLayerName.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingLayerName)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).sortingLayerName");
			}
			if (coherenceSync.TryGetBindingByGuid("31b2e83b-4f43-4709-8912-29042d0b60bd", "sortingLayerID", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingLayerID))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_31b2e83b_4f43_4709_8912_29042d0b60bd();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingLayerID.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingLayerID)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).sortingLayerID");
			}
			if (coherenceSync.TryGetBindingByGuid("cf215880-f8c1-4c78-8a08-62b39f6e83a4", "sortingOrder", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingOrder))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_cf215880_f8c1_4c78_8a08_62b39f6e83a4();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingOrder.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_sortingOrder)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).sortingOrder");
			}
			if (coherenceSync.TryGetBindingByGuid("eb2b888b-e883-491c-9e87-92d2faf1a01c", "allowOcclusionWhenDynamic", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_allowOcclusionWhenDynamic))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_eb2b888b_e883_491c_9e87_92d2faf1a01c();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_allowOcclusionWhenDynamic.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_allowOcclusionWhenDynamic)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).allowOcclusionWhenDynamic");
			}
			if (coherenceSync.TryGetBindingByGuid("09f31160-7485-40ab-a284-2df7eaf788a0", "lightProbeProxyVolumeOverride", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightProbeProxyVolumeOverride))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_09f31160_7485_40ab_a284_2df7eaf788a0();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightProbeProxyVolumeOverride.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightProbeProxyVolumeOverride)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).lightProbeProxyVolumeOverride");
			}
			if (coherenceSync.TryGetBindingByGuid("75194212-5b17-4f2b-9bf0-2afd37a669f9", "probeAnchor", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_probeAnchor))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_75194212_5b17_4f2b_9bf0_2afd37a669f9();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_probeAnchor.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_probeAnchor)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).probeAnchor");
			}
			if (coherenceSync.TryGetBindingByGuid("713ce5cc-bd4d-40cd-829b-da740ac92ec1", "lightmapIndex", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightmapIndex))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_713ce5cc_bd4d_40cd_829b_da740ac92ec1();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightmapIndex.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_lightmapIndex)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).lightmapIndex");
			}
			if (coherenceSync.TryGetBindingByGuid("172b2811-d6ec-4a79-b931-324636a65df9", "realtimeLightmapIndex", out Binding InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_realtimeLightmapIndex))
			{
				var clone = new Binding_daf2ee43443998c43b7845ac6f687f8b_172b2811_d6ec_4a79_b931_324636a65df9();
				InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_realtimeLightmapIndex.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalBackgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_Backgroud_UnityEngine__char_46_SpriteRenderer_6540651817069658648_realtimeLightmapIndex)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.SpriteRenderer).realtimeLightmapIndex");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncBackgroud] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
